// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: airsettle/airsettle/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryVerificationKeyRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryVerificationKeyRequest) Reset()         { *m = QueryVerificationKeyRequest{} }
func (m *QueryVerificationKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVerificationKeyRequest) ProtoMessage()    {}
func (*QueryVerificationKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{2}
}
func (m *QueryVerificationKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerificationKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerificationKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerificationKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerificationKeyRequest.Merge(m, src)
}
func (m *QueryVerificationKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerificationKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerificationKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerificationKeyRequest proto.InternalMessageInfo

func (m *QueryVerificationKeyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryVerificationKeyResponse struct {
	Vkey string `protobuf:"bytes,1,opt,name=vkey,proto3" json:"vkey,omitempty"`
}

func (m *QueryVerificationKeyResponse) Reset()         { *m = QueryVerificationKeyResponse{} }
func (m *QueryVerificationKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerificationKeyResponse) ProtoMessage()    {}
func (*QueryVerificationKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{3}
}
func (m *QueryVerificationKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerificationKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerificationKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerificationKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerificationKeyResponse.Merge(m, src)
}
func (m *QueryVerificationKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerificationKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerificationKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerificationKeyResponse proto.InternalMessageInfo

func (m *QueryVerificationKeyResponse) GetVkey() string {
	if m != nil {
		return m.Vkey
	}
	return ""
}

type QueryShowExecutionLayerByAddressRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryShowExecutionLayerByAddressRequest) Reset() {
	*m = QueryShowExecutionLayerByAddressRequest{}
}
func (m *QueryShowExecutionLayerByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowExecutionLayerByAddressRequest) ProtoMessage()    {}
func (*QueryShowExecutionLayerByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{4}
}
func (m *QueryShowExecutionLayerByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowExecutionLayerByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowExecutionLayerByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowExecutionLayerByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowExecutionLayerByAddressRequest.Merge(m, src)
}
func (m *QueryShowExecutionLayerByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowExecutionLayerByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowExecutionLayerByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowExecutionLayerByAddressRequest proto.InternalMessageInfo

func (m *QueryShowExecutionLayerByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryShowExecutionLayerByAddressResponse struct {
	Exelayer *Exelayer `protobuf:"bytes,1,opt,name=exelayer,proto3" json:"exelayer,omitempty"`
}

func (m *QueryShowExecutionLayerByAddressResponse) Reset() {
	*m = QueryShowExecutionLayerByAddressResponse{}
}
func (m *QueryShowExecutionLayerByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowExecutionLayerByAddressResponse) ProtoMessage()    {}
func (*QueryShowExecutionLayerByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{5}
}
func (m *QueryShowExecutionLayerByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowExecutionLayerByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowExecutionLayerByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowExecutionLayerByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowExecutionLayerByAddressResponse.Merge(m, src)
}
func (m *QueryShowExecutionLayerByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowExecutionLayerByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowExecutionLayerByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowExecutionLayerByAddressResponse proto.InternalMessageInfo

func (m *QueryShowExecutionLayerByAddressResponse) GetExelayer() *Exelayer {
	if m != nil {
		return m.Exelayer
	}
	return nil
}

type QueryShowExecutionLayerByIdRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryShowExecutionLayerByIdRequest) Reset()         { *m = QueryShowExecutionLayerByIdRequest{} }
func (m *QueryShowExecutionLayerByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowExecutionLayerByIdRequest) ProtoMessage()    {}
func (*QueryShowExecutionLayerByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{6}
}
func (m *QueryShowExecutionLayerByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowExecutionLayerByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowExecutionLayerByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowExecutionLayerByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowExecutionLayerByIdRequest.Merge(m, src)
}
func (m *QueryShowExecutionLayerByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowExecutionLayerByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowExecutionLayerByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowExecutionLayerByIdRequest proto.InternalMessageInfo

func (m *QueryShowExecutionLayerByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryShowExecutionLayerByIdResponse struct {
	Exelayer *Exelayer `protobuf:"bytes,1,opt,name=exelayer,proto3" json:"exelayer,omitempty"`
}

func (m *QueryShowExecutionLayerByIdResponse) Reset()         { *m = QueryShowExecutionLayerByIdResponse{} }
func (m *QueryShowExecutionLayerByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowExecutionLayerByIdResponse) ProtoMessage()    {}
func (*QueryShowExecutionLayerByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{7}
}
func (m *QueryShowExecutionLayerByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowExecutionLayerByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowExecutionLayerByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowExecutionLayerByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowExecutionLayerByIdResponse.Merge(m, src)
}
func (m *QueryShowExecutionLayerByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowExecutionLayerByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowExecutionLayerByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowExecutionLayerByIdResponse proto.InternalMessageInfo

func (m *QueryShowExecutionLayerByIdResponse) GetExelayer() *Exelayer {
	if m != nil {
		return m.Exelayer
	}
	return nil
}

type QueryListAllExecutionLayersRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListAllExecutionLayersRequest) Reset()         { *m = QueryListAllExecutionLayersRequest{} }
func (m *QueryListAllExecutionLayersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListAllExecutionLayersRequest) ProtoMessage()    {}
func (*QueryListAllExecutionLayersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{8}
}
func (m *QueryListAllExecutionLayersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAllExecutionLayersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAllExecutionLayersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAllExecutionLayersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAllExecutionLayersRequest.Merge(m, src)
}
func (m *QueryListAllExecutionLayersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAllExecutionLayersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAllExecutionLayersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAllExecutionLayersRequest proto.InternalMessageInfo

func (m *QueryListAllExecutionLayersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListAllExecutionLayersResponse struct {
	Exelayer   []*Exelayer         `protobuf:"bytes,1,rep,name=exelayer,proto3" json:"exelayer,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListAllExecutionLayersResponse) Reset()         { *m = QueryListAllExecutionLayersResponse{} }
func (m *QueryListAllExecutionLayersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListAllExecutionLayersResponse) ProtoMessage()    {}
func (*QueryListAllExecutionLayersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b31ee1de514885b3, []int{9}
}
func (m *QueryListAllExecutionLayersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAllExecutionLayersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAllExecutionLayersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAllExecutionLayersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAllExecutionLayersResponse.Merge(m, src)
}
func (m *QueryListAllExecutionLayersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAllExecutionLayersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAllExecutionLayersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAllExecutionLayersResponse proto.InternalMessageInfo

func (m *QueryListAllExecutionLayersResponse) GetExelayer() []*Exelayer {
	if m != nil {
		return m.Exelayer
	}
	return nil
}

func (m *QueryListAllExecutionLayersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "airsettle.airsettle.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "airsettle.airsettle.QueryParamsResponse")
	proto.RegisterType((*QueryVerificationKeyRequest)(nil), "airsettle.airsettle.QueryVerificationKeyRequest")
	proto.RegisterType((*QueryVerificationKeyResponse)(nil), "airsettle.airsettle.QueryVerificationKeyResponse")
	proto.RegisterType((*QueryShowExecutionLayerByAddressRequest)(nil), "airsettle.airsettle.QueryShowExecutionLayerByAddressRequest")
	proto.RegisterType((*QueryShowExecutionLayerByAddressResponse)(nil), "airsettle.airsettle.QueryShowExecutionLayerByAddressResponse")
	proto.RegisterType((*QueryShowExecutionLayerByIdRequest)(nil), "airsettle.airsettle.QueryShowExecutionLayerByIdRequest")
	proto.RegisterType((*QueryShowExecutionLayerByIdResponse)(nil), "airsettle.airsettle.QueryShowExecutionLayerByIdResponse")
	proto.RegisterType((*QueryListAllExecutionLayersRequest)(nil), "airsettle.airsettle.QueryListAllExecutionLayersRequest")
	proto.RegisterType((*QueryListAllExecutionLayersResponse)(nil), "airsettle.airsettle.QueryListAllExecutionLayersResponse")
}

func init() { proto.RegisterFile("airsettle/airsettle/query.proto", fileDescriptor_b31ee1de514885b3) }

var fileDescriptor_b31ee1de514885b3 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xd1, 0x6a, 0xd4, 0x4c,
	0x14, 0xde, 0xec, 0xdf, 0xbf, 0xd6, 0x11, 0x14, 0xa6, 0xa5, 0x94, 0x6d, 0x4d, 0xcb, 0x08, 0xb6,
	0x08, 0x4d, 0x6c, 0x55, 0xac, 0x50, 0xc5, 0xae, 0xb6, 0x56, 0x2c, 0xb2, 0x46, 0x10, 0xf1, 0x26,
	0xce, 0x6e, 0xc6, 0xec, 0xd0, 0x34, 0x93, 0x66, 0x66, 0xdb, 0x86, 0xd2, 0x1b, 0xaf, 0xbc, 0x14,
	0x7d, 0x0a, 0xdf, 0xc1, 0x07, 0xe8, 0x65, 0x41, 0x04, 0x41, 0x10, 0x69, 0x7d, 0x04, 0x1f, 0x40,
	0x32, 0x99, 0x4d, 0xb7, 0x35, 0xc9, 0xee, 0xda, 0xbb, 0xb3, 0x33, 0xe7, 0x3b, 0xdf, 0xf7, 0x9d,
	0x3d, 0x67, 0x02, 0x26, 0x31, 0x0d, 0x39, 0x11, 0xc2, 0x23, 0xe6, 0x71, 0xb4, 0xd9, 0x22, 0x61,
	0x64, 0x04, 0x21, 0x13, 0x0c, 0x0e, 0xa7, 0xc7, 0x46, 0x1a, 0x55, 0x46, 0x5c, 0xe6, 0x32, 0x79,
	0x6f, 0xc6, 0x51, 0x92, 0x5a, 0x99, 0x70, 0x19, 0x73, 0xe3, 0x42, 0x01, 0x35, 0xb1, 0xef, 0x33,
	0x81, 0x05, 0x65, 0x3e, 0x57, 0xb7, 0xd7, 0x1a, 0x8c, 0x6f, 0x30, 0x6e, 0xd6, 0x31, 0x57, 0x0c,
	0xe6, 0xd6, 0x5c, 0x9d, 0x08, 0x3c, 0x67, 0x06, 0xd8, 0xa5, 0xbe, 0x4c, 0x56, 0xb9, 0x53, 0x59,
	0xaa, 0x02, 0x1c, 0xe2, 0x8d, 0x76, 0x35, 0x94, 0x95, 0x41, 0x76, 0x88, 0x87, 0x23, 0x12, 0x26,
	0x39, 0x68, 0x04, 0xc0, 0x67, 0x31, 0x4f, 0x4d, 0x02, 0x2d, 0xb2, 0xd9, 0x22, 0x5c, 0xa0, 0x1a,
	0x18, 0x3e, 0x71, 0xca, 0x03, 0xe6, 0x73, 0x02, 0xef, 0x80, 0xc1, 0x84, 0x60, 0x4c, 0x9b, 0xd2,
	0x66, 0x2e, 0xcc, 0x8f, 0x1b, 0x19, 0xc6, 0x8d, 0x04, 0x54, 0x1d, 0xd8, 0xff, 0x31, 0x59, 0xb2,
	0x14, 0x00, 0xcd, 0x82, 0x71, 0x59, 0xf1, 0x05, 0x09, 0xe9, 0x1b, 0xda, 0x90, 0x46, 0x9e, 0x90,
	0x48, 0x11, 0xc2, 0x8b, 0xa0, 0x4c, 0x1d, 0x59, 0xf5, 0xbc, 0x55, 0xa6, 0x0e, 0x9a, 0x07, 0x13,
	0xd9, 0xe9, 0x4a, 0x09, 0x04, 0x03, 0x5b, 0xeb, 0x24, 0x52, 0x08, 0x19, 0xa3, 0x07, 0x60, 0x5a,
	0x62, 0x9e, 0x37, 0xd9, 0xf6, 0xf2, 0x0e, 0x69, 0xb4, 0x62, 0xd0, 0x5a, 0xec, 0xb5, 0x1a, 0x2d,
	0x39, 0x4e, 0x48, 0x78, 0xdb, 0x1f, 0x1c, 0x03, 0xe7, 0x70, 0x72, 0xa2, 0x2a, 0xb4, 0x7f, 0x22,
	0x02, 0x66, 0xba, 0x17, 0x49, 0xdb, 0x31, 0xd4, 0xee, 0xa6, 0x6a, 0xc8, 0xe5, 0xcc, 0x86, 0x2c,
	0xab, 0x24, 0x2b, 0x4d, 0x47, 0x37, 0x01, 0xca, 0xa5, 0x79, 0xec, 0xe4, 0x75, 0xe5, 0x35, 0xb8,
	0x52, 0x88, 0x3a, 0xbb, 0x2e, 0x4f, 0xe9, 0x5a, 0xa3, 0x5c, 0x2c, 0x79, 0xde, 0x49, 0x92, 0xb4,
	0x7d, 0x2b, 0x00, 0x1c, 0x8f, 0xa3, 0xa2, 0xb8, 0x6a, 0x24, 0xb3, 0x6b, 0xc4, 0xb3, 0x6b, 0x24,
	0xdb, 0xa1, 0x66, 0xd7, 0xa8, 0x61, 0x97, 0x28, 0xac, 0xd5, 0x81, 0x44, 0x9f, 0x34, 0x65, 0x28,
	0x8f, 0x2e, 0xd3, 0xd0, 0x7f, 0x7d, 0x18, 0x82, 0x8f, 0x4e, 0x48, 0x2d, 0x4b, 0xa9, 0xd3, 0x5d,
	0xa5, 0x26, 0xbc, 0x9d, 0x5a, 0xe7, 0xdf, 0x0d, 0x81, 0xff, 0xa5, 0x56, 0xf8, 0x41, 0x03, 0x83,
	0xc9, 0x8c, 0xc3, 0xe9, 0x4c, 0x19, 0x7f, 0x2f, 0x54, 0x65, 0xa6, 0x7b, 0x62, 0xc2, 0x89, 0x6e,
	0xbd, 0xfd, 0xf2, 0xeb, 0x63, 0xd9, 0x84, 0xb3, 0xf1, 0xce, 0x36, 0x9a, 0x98, 0xfa, 0x7c, 0xd6,
	0x27, 0x62, 0x9b, 0x85, 0xeb, 0x66, 0xfe, 0xc6, 0xc3, 0xcf, 0x1a, 0xb8, 0x74, 0x6a, 0x59, 0xe0,
	0xf5, 0x7c, 0xd2, 0xec, 0x35, 0xac, 0xcc, 0xf5, 0x81, 0x50, 0x7a, 0x1f, 0x4a, 0xbd, 0xf7, 0xe0,
	0x62, 0x8f, 0x7a, 0xb7, 0x3a, 0xea, 0xd8, 0xeb, 0x24, 0x32, 0x77, 0xa9, 0xb3, 0x07, 0x7f, 0x6b,
	0x60, 0xbc, 0x60, 0xe5, 0xe0, 0x62, 0xbe, 0xb0, 0xee, 0xeb, 0x5e, 0xb9, 0xfb, 0x8f, 0x68, 0x65,
	0xf1, 0xa5, 0xb4, 0x68, 0xc1, 0x5a, 0x8f, 0x16, 0x79, 0x93, 0x6d, 0xdb, 0xa4, 0x5d, 0xd4, 0x96,
	0x83, 0x68, 0xd7, 0x23, 0x5b, 0xbd, 0x31, 0xe6, 0xae, 0x0a, 0xf6, 0xe0, 0x77, 0x0d, 0x8c, 0x66,
	0x2f, 0x33, 0xbc, 0xdd, 0x9f, 0xe6, 0xf4, 0xd1, 0xa8, 0x2c, 0xf4, 0x0f, 0x54, 0x3e, 0x9f, 0x4a,
	0x9f, 0xab, 0x70, 0xe5, 0x8c, 0x3e, 0xa9, 0x93, 0xfc, 0xa9, 0x5f, 0x35, 0x30, 0x9a, 0xbd, 0xd9,
	0x45, 0xee, 0x0a, 0x9f, 0x9e, 0x22, 0x77, 0xc5, 0x8f, 0x08, 0x5a, 0x95, 0xee, 0xaa, 0xf0, 0x7e,
	0x8f, 0xee, 0x3c, 0xca, 0x85, 0x8d, 0x3d, 0xef, 0xb4, 0x43, 0x5e, 0xb5, 0xf6, 0x0f, 0x75, 0xed,
	0xe0, 0x50, 0xd7, 0x7e, 0x1e, 0xea, 0xda, 0xfb, 0x23, 0xbd, 0x74, 0x70, 0xa4, 0x97, 0xbe, 0x1d,
	0xe9, 0xa5, 0x57, 0x0b, 0x2e, 0x15, 0xcd, 0x56, 0xdd, 0x68, 0xb0, 0x8d, 0x42, 0x96, 0x9d, 0x8e,
	0x58, 0x44, 0x01, 0xe1, 0xf5, 0x41, 0xf9, 0x39, 0xbe, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0x43, 0x25, 0x8b, 0x6c, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of VerificationKey items.
	VerificationKey(ctx context.Context, in *QueryVerificationKeyRequest, opts ...grpc.CallOption) (*QueryVerificationKeyResponse, error)
	// Queries a list of ShowExecutionLayerByAddress items.
	ShowExecutionLayerByAddress(ctx context.Context, in *QueryShowExecutionLayerByAddressRequest, opts ...grpc.CallOption) (*QueryShowExecutionLayerByAddressResponse, error)
	// Queries a list of ShowExecutionLayerById items.
	ShowExecutionLayerById(ctx context.Context, in *QueryShowExecutionLayerByIdRequest, opts ...grpc.CallOption) (*QueryShowExecutionLayerByIdResponse, error)
	// Queries a list of ListAllExecutionLayers items.
	ListAllExecutionLayers(ctx context.Context, in *QueryListAllExecutionLayersRequest, opts ...grpc.CallOption) (*QueryListAllExecutionLayersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/airsettle.airsettle.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerificationKey(ctx context.Context, in *QueryVerificationKeyRequest, opts ...grpc.CallOption) (*QueryVerificationKeyResponse, error) {
	out := new(QueryVerificationKeyResponse)
	err := c.cc.Invoke(ctx, "/airsettle.airsettle.Query/VerificationKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowExecutionLayerByAddress(ctx context.Context, in *QueryShowExecutionLayerByAddressRequest, opts ...grpc.CallOption) (*QueryShowExecutionLayerByAddressResponse, error) {
	out := new(QueryShowExecutionLayerByAddressResponse)
	err := c.cc.Invoke(ctx, "/airsettle.airsettle.Query/ShowExecutionLayerByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowExecutionLayerById(ctx context.Context, in *QueryShowExecutionLayerByIdRequest, opts ...grpc.CallOption) (*QueryShowExecutionLayerByIdResponse, error) {
	out := new(QueryShowExecutionLayerByIdResponse)
	err := c.cc.Invoke(ctx, "/airsettle.airsettle.Query/ShowExecutionLayerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListAllExecutionLayers(ctx context.Context, in *QueryListAllExecutionLayersRequest, opts ...grpc.CallOption) (*QueryListAllExecutionLayersResponse, error) {
	out := new(QueryListAllExecutionLayersResponse)
	err := c.cc.Invoke(ctx, "/airsettle.airsettle.Query/ListAllExecutionLayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of VerificationKey items.
	VerificationKey(context.Context, *QueryVerificationKeyRequest) (*QueryVerificationKeyResponse, error)
	// Queries a list of ShowExecutionLayerByAddress items.
	ShowExecutionLayerByAddress(context.Context, *QueryShowExecutionLayerByAddressRequest) (*QueryShowExecutionLayerByAddressResponse, error)
	// Queries a list of ShowExecutionLayerById items.
	ShowExecutionLayerById(context.Context, *QueryShowExecutionLayerByIdRequest) (*QueryShowExecutionLayerByIdResponse, error)
	// Queries a list of ListAllExecutionLayers items.
	ListAllExecutionLayers(context.Context, *QueryListAllExecutionLayersRequest) (*QueryListAllExecutionLayersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VerificationKey(ctx context.Context, req *QueryVerificationKeyRequest) (*QueryVerificationKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationKey not implemented")
}
func (*UnimplementedQueryServer) ShowExecutionLayerByAddress(ctx context.Context, req *QueryShowExecutionLayerByAddressRequest) (*QueryShowExecutionLayerByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowExecutionLayerByAddress not implemented")
}
func (*UnimplementedQueryServer) ShowExecutionLayerById(ctx context.Context, req *QueryShowExecutionLayerByIdRequest) (*QueryShowExecutionLayerByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowExecutionLayerById not implemented")
}
func (*UnimplementedQueryServer) ListAllExecutionLayers(ctx context.Context, req *QueryListAllExecutionLayersRequest) (*QueryListAllExecutionLayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllExecutionLayers not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airsettle.airsettle.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerificationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerificationKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerificationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airsettle.airsettle.Query/VerificationKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerificationKey(ctx, req.(*QueryVerificationKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowExecutionLayerByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowExecutionLayerByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowExecutionLayerByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airsettle.airsettle.Query/ShowExecutionLayerByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowExecutionLayerByAddress(ctx, req.(*QueryShowExecutionLayerByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowExecutionLayerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowExecutionLayerByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowExecutionLayerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airsettle.airsettle.Query/ShowExecutionLayerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowExecutionLayerById(ctx, req.(*QueryShowExecutionLayerByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListAllExecutionLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListAllExecutionLayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListAllExecutionLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airsettle.airsettle.Query/ListAllExecutionLayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListAllExecutionLayers(ctx, req.(*QueryListAllExecutionLayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "airsettle.airsettle.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VerificationKey",
			Handler:    _Query_VerificationKey_Handler,
		},
		{
			MethodName: "ShowExecutionLayerByAddress",
			Handler:    _Query_ShowExecutionLayerByAddress_Handler,
		},
		{
			MethodName: "ShowExecutionLayerById",
			Handler:    _Query_ShowExecutionLayerById_Handler,
		},
		{
			MethodName: "ListAllExecutionLayers",
			Handler:    _Query_ListAllExecutionLayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "airsettle/airsettle/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVerificationKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerificationKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerificationKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerificationKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerificationKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerificationKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vkey) > 0 {
		i -= len(m.Vkey)
		copy(dAtA[i:], m.Vkey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Vkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowExecutionLayerByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowExecutionLayerByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowExecutionLayerByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowExecutionLayerByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowExecutionLayerByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowExecutionLayerByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exelayer != nil {
		{
			size, err := m.Exelayer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowExecutionLayerByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowExecutionLayerByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowExecutionLayerByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowExecutionLayerByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowExecutionLayerByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowExecutionLayerByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exelayer != nil {
		{
			size, err := m.Exelayer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListAllExecutionLayersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAllExecutionLayersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAllExecutionLayersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListAllExecutionLayersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAllExecutionLayersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAllExecutionLayersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Exelayer) > 0 {
		for iNdEx := len(m.Exelayer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Exelayer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVerificationKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerificationKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Vkey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowExecutionLayerByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowExecutionLayerByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Exelayer != nil {
		l = m.Exelayer.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowExecutionLayerByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowExecutionLayerByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Exelayer != nil {
		l = m.Exelayer.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListAllExecutionLayersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListAllExecutionLayersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Exelayer) > 0 {
		for _, e := range m.Exelayer {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerificationKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerificationKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerificationKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerificationKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerificationKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerificationKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowExecutionLayerByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowExecutionLayerByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exelayer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Exelayer == nil {
				m.Exelayer = &Exelayer{}
			}
			if err := m.Exelayer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowExecutionLayerByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowExecutionLayerByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowExecutionLayerByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exelayer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Exelayer == nil {
				m.Exelayer = &Exelayer{}
			}
			if err := m.Exelayer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAllExecutionLayersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAllExecutionLayersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAllExecutionLayersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAllExecutionLayersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAllExecutionLayersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAllExecutionLayersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exelayer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Exelayer = append(m.Exelayer, &Exelayer{})
			if err := m.Exelayer[len(m.Exelayer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
